build:
  image: inovex/gitlab-ci-android
  stage: build
  variables:
    GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  before_script:
    - export GRADLE_USER_HOME=$(pwd)/.gradle
    - export JAVA_HOME=/usr/lib/jvm/java-17-openjdk-amd64
    - chmod +x ./gradlew
  cache:
    key: ${CI_PROJECT_ID}
    paths:
      - .gradle/
  script:
    - |
      if [ ! -f debug.keystore ]; then
        keytool -genkeypair -v -keystore debug.keystore -storepass android -alias androiddebugkey -keypass android -keyalg RSA -keysize 2048 -validity 10000 -dname "CN=Android Debug,O=Android,C=US"
      fi
    - ./gradlew assembleDebug --no-daemon
  artifacts:
    expire_in: 2 weeks
    paths:
      - app/build/outputs/apk/debug/*.apk
